version: "3.8"

services:
  app:
    build: .
    container_name: ep_app
    # Add the command to start Gunicorn with a longer timeout
    command: gunicorn -b 0.0.0.0:8000 --workers=1 --timeout=1200 app:app
    env_file:
      - .env
    environment:
      # If you rely on environment vars in .env
      # or override them here:
      DB_HOST: leda.geodan.nl
      ENERGYPLUS_VERSION: "22.2.0"
    volumes:
      - ./data:/usr/src/app/data
      - ./output:/usr/src/app/output
      - ./user_configs:/usr/src/app/user_configs
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: ep_db
    restart: always
    environment:
      POSTGRES_DB: research
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
