# Auto-generated from materials.xlsx

"""
materials_lookup.py

Defines a dictionary `material_lookup` from your Excel table.
"""

material_lookup = {'nan': {'obj_type': 'MATERIAL',
         'Name': 'Not_Applicable',
         'Description': 'Placeholder for assemblies that have no relevant '
                        'opaque or window material.'},
 'Concrete_200mm': {'obj_type': 'MATERIAL',
                    'Name': 'Concrete_200mm',
                    'Roughness': 'MediumRough',
                    'Thickness_range': (0.195, 0.205),
                    'Conductivity_range': (1.5, 1.7),
                    'Density_range': (2250, 2350),
                    'Specific_Heat_range': (850, 950),
                    'Thermal_Absorptance_range': (0.9, 0.9),
                    'Solar_Absorptance_range': (0.7, 0.7),
                    'Visible_Absorptance_range': (0.7, 0.7)},
 'GroundContactFloor_Generic': {'obj_type': 'MATERIAL',
                                'Name': 'GroundContactFloor_Generic',
                                'Roughness': 'MediumRough',
                                'Thickness_range': (0.1, 0.12),
                                'Conductivity_range': (1.0, 1.2),
                                'Density_range': (2100, 2300),
                                'Specific_Heat_range': (850, 900),
                                'Thermal_Absorptance_range': (0.9, 0.9),
                                'Solar_Absorptance_range': (0.7, 0.7),
                                'Visible_Absorptance_range': (0.7, 0.7)},
 'InternalFloor_Generic': {'obj_type': 'MATERIAL',
                           'Name': 'InternalFloor_Generic',
                           'Roughness': 'MediumSmooth',
                           'Thickness_range': (0.12, 0.15),
                           'Conductivity_range': (0.7, 1.2),
                           'Density_range': (1800, 2000),
                           'Specific_Heat_range': (800, 900),
                           'Thermal_Absorptance_range': (0.9, 0.9),
                           'Solar_Absorptance_range': (0.7, 0.7),
                           'Visible_Absorptance_range': (0.7, 0.7)},
 'Insulated_Roof_R5': {'obj_type': 'MATERIAL:NOMASS',
                       'Name': 'Insulated_Roof_R5',
                       'Roughness': 'MediumRough',
                       'Thermal_Absorptance_range': (0.9, 0.9),
                       'Solar_Absorptance_range': (0.7, 0.7),
                       'Visible_Absorptance_range': (0.7, 0.7),
                       'Thermal_Resistance_range': (4.0, 5.0)},
 'InteriorWall_Generic': {'obj_type': 'MATERIAL',
                          'Name': 'InteriorWall_Generic',
                          'Roughness': 'MediumSmooth',
                          'Thickness_range': (0.1, 0.15),
                          'Conductivity_range': (0.4, 0.6),
                          'Density_range': (700, 900),
                          'Specific_Heat_range': (800, 1000),
                          'Thermal_Absorptance_range': (0.9, 0.9),
                          'Solar_Absorptance_range': (0.7, 0.7),
                          'Visible_Absorptance_range': (0.7, 0.7)},
 'DoorPanel_Range': {'obj_type': 'MATERIAL',
                     'Name': 'DoorPanel_Range',
                     'Roughness': 'MediumRough',
                     'Thickness_range': (0.14, 0.25),
                     'Conductivity_range': (1.4, 1.7),
                     'Density_range': (600, 700),
                     'Specific_Heat_range': (2200, 2400),
                     'Thermal_Absorptance_range': (0.9, 0.9),
                     'Solar_Absorptance_range': (0.7, 0.7),
                     'Visible_Absorptance_range': (0.7, 0.7)},
 'Glazing_Clear_3mm': {'obj_type': 'WINDOWMATERIAL:GLAZING',
                       'Name': 'Glazing_Clear_3mm',
                       'Optical_Data_Type': 'SpectralAverage',
                       'Solar_Diffusing': 'No',
                       'Thickness_range': (0.003, 0.003),
                       'Conductivity_range': (0.95, 1.05),
                       'Solar_Transmittance_range': (0.76, 0.78),
                       'Front_Solar_Reflectance_range': (0.07, 0.08),
                       'Back_Solar_Reflectance_range': (0.07, 0.08),
                       'Visible_Transmittance_range': (0.86, 0.88),
                       'Front_Visible_Reflectance_range': (0.06, 0.07),
                       'Back_Visible_Reflectance_range': (0.06, 0.07),
                       'Front_IR_Emissivity_range': (0.84, 0.84),
                       'Back_IR_Emissivity_range': (0.84, 0.84),
                       'Dirt_Correction_Factor_range': (1.0, 1.0),
                       'IR_Transmittance': 0.0},
 'Glazing_Clear_3mm_Post': {'obj_type': 'WINDOWMATERIAL:GLAZING',
                            'Name': 'Glazing_Clear_3mm_Post',
                            'Optical_Data_Type': 'SpectralAverage',
                            'Solar_Diffusing': 'No',
                            'Thickness_range': (0.003, 0.003),
                            'Conductivity_range': (1.0, 1.0),
                            'Solar_Transmittance_range': (0.75, 0.75),
                            'Front_Solar_Reflectance_range': (0.07, 0.07),
                            'Back_Solar_Reflectance_range': (0.07, 0.07),
                            'Visible_Transmittance_range': (0.85, 0.85),
                            'Front_Visible_Reflectance_range': (0.07, 0.07),
                            'Back_Visible_Reflectance_range': (0.07, 0.07),
                            'Front_IR_Emissivity_range': (0.84, 0.84),
                            'Back_IR_Emissivity_range': (0.84, 0.84),
                            'Dirt_Correction_Factor_range': (1.0, 1.0),
                            'IR_Transmittance': 0.0},
 'DoorPanel_Range2': {'obj_type': 'MATERIAL',
                      'Name': 'DoorPanel_Range2',
                      'Roughness': 'MediumSmooth',
                      'Thickness_range': (0.04, 0.05),
                      'Conductivity_range': (0.4, 0.5),
                      'Density_range': (600, 700),
                      'Specific_Heat_range': (1200, 1300),
                      'Thermal_Absorptance_range': (0.9, 0.9),
                      'Solar_Absorptance_range': (0.7, 0.7),
                      'Visible_Absorptance_range': (0.7, 0.7)},
 'Ceiling_Insulation_R3': {'obj_type': 'MATERIAL',
                           'Name': 'Ceiling_Insulation_R3',
                           'Roughness': 'MediumRough',
                           'Thickness_range': (0.02, 0.03),
                           'Conductivity_range': (0.035, 0.045),
                           'Density_range': (20, 25),
                           'Specific_Heat_range': (1400, 1500),
                           'Thermal_Absorptance_range': (0.9, 0.9),
                           'Solar_Absorptance_range': (0.7, 0.7),
                           'Visible_Absorptance_range': (0.7, 0.7)},
 'Roof_Insulation_R5': {'obj_type': 'MATERIAL',
                        'Name': 'Roof_Insulation_R5',
                        'Roughness': 'MediumRough',
                        'Thickness_range': (0.04, 0.05),
                        'Conductivity_range': (0.03, 0.04),
                        'Density_range': (25, 30),
                        'Specific_Heat_range': (1400, 1500),
                        'Thermal_Absorptance_range': (0.9, 0.9),
                        'Solar_Absorptance_range': (0.7, 0.7),
                        'Visible_Absorptance_range': (0.7, 0.7)},
 'AdiabaticWall_Generic': {'obj_type': 'MATERIAL',
                           'Name': 'AdiabaticWall_Generic',
                           'Roughness': 'MediumSmooth',
                           'Thickness_range': (0.15, 0.2),
                           'Conductivity_range': (0.3, 0.4),
                           'Density_range': (200, 300),
                           'Specific_Heat_range': (1000, 1100),
                           'Thermal_Absorptance_range': (0.9, 0.9),
                           'Solar_Absorptance_range': (0.7, 0.7),
                           'Visible_Absorptance_range': (0.7, 0.7)}}
