# This file is automatically generated. Do not edit manually.
material_lookup = {
    "Default_Material": {
        "Roughness": "MediumRough",
    },
    "InteriorWall_Generic_R0.5": {
        "Roughness": "MediumSmooth",
    },
    "InternalFloor_Generic_R1.0": {
        "Roughness": "MediumSmooth",
    },
    "GroundFloor_R0.15": {
        "Roughness": "MediumRough",
    },
    "GroundFloor_R0.17": {
        "Roughness": "MediumRough",
    },
    "GroundFloor_R0.52": {
        "Roughness": "MediumRough",
    },
    "GroundFloor_R1.30": {
        "Roughness": "MediumRough",
    },
    "GroundFloor_R2.5": {
        "Roughness": "MediumRough",
    },
    "GroundFloor_R3.5": {
        "Roughness": "MediumRough",
    },
    "ExtWall_R0.19": {
        "Roughness": "MediumRough",
    },
    "ExtWall_R0.35": {
        "Roughness": "MediumRough",
    },
    "ExtWall_R0.43": {
        "Roughness": "MediumRough",
    },
    "ExtWall_R1.30": {
        "Roughness": "MediumRough",
    },
    "ExtWall_R1.7": {
        "Roughness": "MediumRough",
    },
    "ExtWall_R2.5": {
        "Roughness": "MediumRough",
    },
    "ExtWall_R4.5": {
        "Roughness": "MediumRough",
    },
    "Roof_R0.22": {
        "Roughness": "MediumRough",
    },
    "Roof_R0.25": {
        "Roughness": "MediumRough",
    },
    "Roof_R0.35": {
        "Roughness": "MediumRough",
    },
    "Roof_R0.43": {
        "Roughness": "MediumRough",
    },
    "Roof_R0.72": {
        "Roughness": "MediumRough",
    },
    "Roof_R0.86": {
        "Roughness": "MediumRough",
    },
    "Roof_R1.03": {
        "Roughness": "MediumRough",
    },
    "Roof_R1.30": {
        "Roughness": "MediumRough",
    },
    "Roof_R1.71": {
        "Roughness": "MediumRough",
    },
    "Roof_R2.5": {
        "Roughness": "MediumRough",
    },
    "Roof_R3.5": {
        "Roughness": "MediumRough",
    },
    "Roof_R6.0": {
        "Roughness": "MediumRough",
    },
    "Door_U3.4": {
        "Roughness": "MediumRough",
    },
    "Door_U2.0": {
        "Roughness": "MediumRough",
    },
    "Door_U1.4": {
        "Roughness": "MediumRough",
    },
    "Window_U5.1": {
        "Optical_Data_Type": "(0.792, 0.808)",
    },
    "Window_U4.0": {
        "Optical_Data_Type": "(0.742, 0.758)",
    },
    "Window_U2.9": {
        "Optical_Data_Type": "(0.693, 0.707)",
    },
    "Window_U2.0": {
        "Optical_Data_Type": "(0.594, 0.606)",
    },
    "Window_U1.8": {
        "Optical_Data_Type": "(0.544, 0.556)",
    },
    "Window_U1.4": {
        "Optical_Data_Type": "(0.446, 0.455)",
    },
    "NR_InteriorWall_R0.5": {
        "Roughness": "MediumSmooth",
    },
    "NR_InternalFloor_R1.0": {
        "Roughness": "MediumSmooth",
    },
    "NR_GroundFloor_U2.8": {
        "Roughness": "MediumRough",
    },
    "NR_GroundFloor_U2.4": {
        "Roughness": "MediumRough",
    },
    "NR_GroundFloor_U1.8": {
        "Roughness": "MediumRough",
    },
    "NR_GroundFloor_U1.3": {
        "Roughness": "MediumRough",
    },
    "NR_GroundFloor_U0.9": {
        "Roughness": "MediumRough",
    },
    "NR_GroundFloor_U0.8": {
        "Roughness": "MediumRough",
    },
    "NR_GroundFloor_U0.5": {
        "Roughness": "MediumRough",
    },
    "NR_GroundFloor_U0.35": {
        "Roughness": "MediumRough",
    },
    "NR_GroundFloor_U0.3": {
        "Roughness": "MediumRough",
    },
    "NR_GroundFloor_U0.2": {
        "Roughness": "MediumRough",
    },
    "NR_ExtWall_U3.0": {
        "Roughness": "MediumRough",
    },
    "NR_ExtWall_U2.5": {
        "Roughness": "MediumRough",
    },
    "NR_ExtWall_U2.0": {
        "Roughness": "MediumRough",
    },
    "NR_ExtWall_U1.5": {
        "Roughness": "MediumRough",
    },
    "NR_ExtWall_U1.0": {
        "Roughness": "MediumRough",
    },
    "NR_ExtWall_U0.7": {
        "Roughness": "MediumRough",
    },
    "NR_ExtWall_U0.6": {
        "Roughness": "MediumRough",
    },
    "NR_ExtWall_U0.4": {
        "Roughness": "MediumRough",
    },
    "NR_ExtWall_U0.3": {
        "Roughness": "MediumRough",
    },
    "NR_ExtWall_U0.2": {
        "Roughness": "MediumRough",
    },
    "NR_Roof_U3.5": {
        "Roughness": "MediumRough",
    },
    "NR_Roof_U3.0": {
        "Roughness": "MediumRough",
    },
    "NR_Roof_U2.5": {
        "Roughness": "MediumRough",
    },
    "NR_Roof_U1.8": {
        "Roughness": "MediumRough",
    },
    "NR_Roof_U1.2": {
        "Roughness": "MediumRough",
    },
    "NR_Roof_U0.8": {
        "Roughness": "MediumRough",
    },
    "NR_Roof_U0.7": {
        "Roughness": "MediumRough",
    },
    "NR_Roof_U0.5": {
        "Roughness": "MediumRough",
    },
    "NR_Roof_U0.35": {
        "Roughness": "MediumRough",
    },
    "NR_Roof_U0.3": {
        "Roughness": "MediumRough",
    },
    "NR_Roof_U0.18": {
        "Roughness": "MediumRough",
    },
    "NR_Door_U4.0": {
        "Roughness": "MediumRough",
    },
    "NR_Door_U3.4": {
        "Roughness": "MediumRough",
    },
    "NR_Door_U2.8": {
        "Roughness": "MediumRough",
    },
    "NR_Door_U2.2": {
        "Roughness": "MediumRough",
    },
    "NR_Door_U1.8": {
        "Roughness": "MediumRough",
    },
    "NR_Door_U1.5": {
        "Roughness": "MediumRough",
    },
    "NR_Door_U1.2": {
        "Roughness": "MediumRough",
    },
    "NR_Door_U1.0": {
        "Roughness": "MediumRough",
    },
    "NR_Window_U5.8_SHGC0.80": {
        "Optical_Data_Type": "(0.792, 0.808)",
    },
    "NR_Window_U5.1_SHGC0.80": {
        "Optical_Data_Type": "(0.792, 0.808)",
    },
    "NR_Window_U4.0_SHGC0.70": {
        "Optical_Data_Type": "(0.693, 0.707)",
    },
    "NR_Window_U2.9_SHGC0.60": {
        "Optical_Data_Type": "(0.594, 0.606)",
    },
    "NR_Window_U2.2_SHGC0.55": {
        "Optical_Data_Type": "(0.544, 0.556)",
    },
    "NR_Window_U1.8_SHGC0.50": {
        "Optical_Data_Type": "(0.495, 0.505)",
    },
    "NR_Window_U1.4_SHGC0.45": {
        "Optical_Data_Type": "(0.446, 0.455)",
    },
    "NR_Window_U1.1_SHGC0.40": {
        "Optical_Data_Type": "(0.396, 0.404)",
    },
    "Glazing_Clear_3mm": {
        "IR_Transmittance": 0.0,
        "Optical_Data_Type": "SpectralAverage",
        "Solar_Diffusing": "No",
    },
    "Name": {
        "Roughness": "Roughness",
        "IR_Transmittance": "IR_Transmittance",
        "Optical_Data_Type": "Optical_Data_Type",
        "Solar_Diffusing": "Solar_Diffusing",
    },
}
