# Auto-generated from Vent_lookup.xlsx

"""
ventilation_lookup.py
Large nested dict from Excel.
"""

ventilation_lookup = {'scenario1': {'post_calibration': {'residential_infiltration_range': {'Corner House': (1.3,
                                                                                        1.3),
                                                                       'Apartment': (0.9,
                                                                                     0.9),
                                                                       'Terrace or Semi-detached House': (1.1,
                                                                                                          1.1),
                                                                       'Detached House': (1.3,
                                                                                          1.3),
                                                                       'Two-and-a-half-story House': (1.2,
                                                                                                      1.2),
                                                                       'other_res': (1.1,
                                                                                     1.1)},
                                    'non_res_infiltration_range': {'Meeting Function': (0.6,
                                                                                        0.6),
                                                                   'Healthcare Function': (0.7,
                                                                                           0.7),
                                                                   'Sport Function': (0.5,
                                                                                      0.5),
                                                                   'Cell Function': (0.6,
                                                                                     0.6),
                                                                   'Retail Function': (0.7,
                                                                                       0.7),
                                                                   'Industrial Function': (0.7,
                                                                                           0.7),
                                                                   'Accommodation Function': (0.6,
                                                                                              0.6),
                                                                   'Office Function': (0.6,
                                                                                       0.6),
                                                                   'Education Function': (0.6,
                                                                                          0.6),
                                                                   'Other Use Function': (0.6,
                                                                                          0.6),
                                                                   'other_nonres': (0.6,
                                                                                    0.6)},
                                    'year_factor_range': {'< 1945': (2.2, 2.2),
                                                          '1945 - 1964': (1.9,
                                                                          1.9),
                                                          '1965 - 1974': (1.6,
                                                                          1.6),
                                                          '1975 - 1991': (1.4,
                                                                          1.4),
                                                          '1992 - 2005': (1.2,
                                                                          1.2),
                                                          '2006 - 2014': (1.0,
                                                                          1.0),
                                                          '2015 and later': (0.8,
                                                                             0.8)},
                                    'system_control_range_res': {'B': {'f_ctrl_range': (0.57,
                                                                                        0.57)},
                                                                 'C': {'f_ctrl_range': (0.85,
                                                                                        0.85)},
                                                                 'D': {'f_ctrl_range': (1.0,
                                                                                        1.0)},
                                                                 'A': {'f_ctrl_range': (1.0,
                                                                                        1.0)}},
                                    'system_control_range_nonres': {'D': {'f_ctrl_range': (0.8,
                                                                                           0.8)},
                                                                    'C': {'f_ctrl_range': (0.65,
                                                                                           0.65)},
                                                                    'B': {'f_ctrl_range': (0.85,
                                                                                           0.85)},
                                                                    'A': {'f_ctrl_range': (1.0,
                                                                                           1.0)}},
                                    'fan_pressure_range': {'res_mech': (50.0,
                                                                        50.0),
                                                           'nonres_intake': (100.0,
                                                                             100.0),
                                                           'nonres_exhaust': (150.0,
                                                                              150.0)},
                                    'hrv_sensible_eff_range': (0.75, 0.75),
                                    'system_type_map': {'residential': {'< 1945': {'Corner House': 'B',
                                                                                   'Apartment': 'C',
                                                                                   'Terrace or Semi-detached House': 'C',
                                                                                   'Detached House': 'D',
                                                                                   'Two-and-a-half-story House': 'A'},
                                                                        '1945 - 1964': {'Corner House': 'A',
                                                                                        'Apartment': 'C',
                                                                                        'Terrace or Semi-detached House': 'D',
                                                                                        'Detached House': 'D',
                                                                                        'Two-and-a-half-story House': 'C'},
                                                                        '1965 - 1974': {'Corner House': 'C',
                                                                                        'Apartment': 'B',
                                                                                        'Terrace or Semi-detached House': 'C',
                                                                                        'Detached House': 'D',
                                                                                        'Two-and-a-half-story House': 'A'},
                                                                        '1975 - 1991': {'Corner House': 'B',
                                                                                        'Apartment': 'C',
                                                                                        'Terrace or Semi-detached House': 'B',
                                                                                        'Detached House': 'C',
                                                                                        'Two-and-a-half-story House': 'A'},
                                                                        '1992 - 2005': {'Corner House': 'C',
                                                                                        'Apartment': 'A',
                                                                                        'Terrace or Semi-detached House': 'C',
                                                                                        'Detached House': 'D',
                                                                                        'Two-and-a-half-story House': 'D'},
                                                                        '2006 - 2014': {'Corner House': 'D',
                                                                                        'Apartment': 'D',
                                                                                        'Terrace or Semi-detached House': 'C',
                                                                                        'Detached House': 'C',
                                                                                        'Two-and-a-half-story House': 'A'},
                                                                        '2015 and later': {'Corner House': 'D',
                                                                                           'Apartment': 'C',
                                                                                           'Terrace or Semi-detached House': 'A',
                                                                                           'Detached House': 'B',
                                                                                           'Two-and-a-half-story House': 'D'}},
                                                        'non_residential': {'< 1945': {'Meeting Function': 'D',
                                                                                       'Healthcare Function': 'D',
                                                                                       'Sport Function': 'C',
                                                                                       'Cell Function': 'C',
                                                                                       'Retail Function': 'B',
                                                                                       'Industrial Function': 'B',
                                                                                       'Accommodation Function': 'A',
                                                                                       'Office Function': 'C',
                                                                                       'Education Function': 'A',
                                                                                       'Other Use Function': 'B'},
                                                                            '1945 - 1964': {'Meeting Function': 'C',
                                                                                            'Healthcare Function': 'D',
                                                                                            'Sport Function': 'B',
                                                                                            'Cell Function': 'C',
                                                                                            'Retail Function': 'B',
                                                                                            'Industrial Function': 'A',
                                                                                            'Accommodation Function': 'D',
                                                                                            'Office Function': 'D',
                                                                                            'Education Function': 'B',
                                                                                            'Other Use Function': 'A'},
                                                                            '1965 - 1974': {'Meeting Function': 'B',
                                                                                            'Healthcare Function': 'C',
                                                                                            'Sport Function': 'B',
                                                                                            'Cell Function': 'C',
                                                                                            'Retail Function': 'C',
                                                                                            'Industrial Function': 'C',
                                                                                            'Accommodation Function': 'B',
                                                                                            'Office Function': 'B',
                                                                                            'Education Function': 'D',
                                                                                            'Other Use Function': 'A'},
                                                                            '1975 - 1991': {'Meeting Function': 'C',
                                                                                            'Healthcare Function': 'D',
                                                                                            'Sport Function': 'B',
                                                                                            'Cell Function': 'C',
                                                                                            'Retail Function': 'B',
                                                                                            'Industrial Function': 'A',
                                                                                            'Accommodation Function': 'D',
                                                                                            'Office Function': 'D',
                                                                                            'Education Function': 'B',
                                                                                            'Other Use Function': 'A'},
                                                                            '1992 - 2005': {'Meeting Function': 'A',
                                                                                            'Healthcare Function': 'D',
                                                                                            'Sport Function': 'C',
                                                                                            'Cell Function': 'C',
                                                                                            'Retail Function': 'B',
                                                                                            'Industrial Function': 'B',
                                                                                            'Accommodation Function': 'A',
                                                                                            'Office Function': 'C',
                                                                                            'Education Function': 'A',
                                                                                            'Other Use Function': 'B'},
                                                                            '2006 - 2014': {'Meeting Function': 'C',
                                                                                            'Healthcare Function': 'D',
                                                                                            'Sport Function': 'B',
                                                                                            'Cell Function': 'C',
                                                                                            'Retail Function': 'B',
                                                                                            'Industrial Function': 'A',
                                                                                            'Accommodation Function': 'D',
                                                                                            'Office Function': 'D',
                                                                                            'Education Function': 'B',
                                                                                            'Other Use Function': 'A'},
                                                                            '2015 and later': {'Meeting Function': 'A',
                                                                                               'Healthcare Function': 'D',
                                                                                               'Sport Function': 'C',
                                                                                               'Cell Function': 'C',
                                                                                               'Retail Function': 'B',
                                                                                               'Industrial Function': 'B',
                                                                                               'Accommodation Function': 'A',
                                                                                               'Office Function': 'C',
                                                                                               'Education Function': 'A',
                                                                                               'Other Use Function': 'B'}}}},
               'pre_calibration': {'residential_infiltration_range': {'Corner House': (1.3,
                                                                                       1.3),
                                                                      'Apartment': (0.9,
                                                                                    0.9),
                                                                      'Terrace or Semi-detached House': (1.1,
                                                                                                         1.1),
                                                                      'Detached House': (1.3,
                                                                                         1.3),
                                                                      'Two-and-a-half-story House': (1.2,
                                                                                                     1.2),
                                                                      'other_res': (1.1,
                                                                                    1.1)},
                                   'non_res_infiltration_range': {'Meeting Function': (0.6,
                                                                                       0.6),
                                                                  'Healthcare Function': (0.7,
                                                                                          0.7),
                                                                  'Sport Function': (0.5,
                                                                                     0.5),
                                                                  'Cell Function': (0.6,
                                                                                    0.6),
                                                                  'Retail Function': (0.7,
                                                                                      0.7),
                                                                  'Industrial Function': (0.7,
                                                                                          0.7),
                                                                  'Accommodation Function': (0.6,
                                                                                             0.6),
                                                                  'Office Function': (0.6,
                                                                                      0.6),
                                                                  'Education Function': (0.6,
                                                                                         0.6),
                                                                  'Other Use Function': (0.6,
                                                                                         0.6),
                                                                  'other_nonres': (0.6,
                                                                                   0.6)},
                                   'year_factor_range': {'< 1945': (2.2, 2.2),
                                                         '1945 - 1964': (1.9,
                                                                         1.9),
                                                         '1965 - 1974': (1.6,
                                                                         1.6),
                                                         '1975 - 1991': (1.4,
                                                                         1.4),
                                                         '1992 - 2005': (1.2,
                                                                         1.2),
                                                         '2006 - 2014': (1.0,
                                                                         1.0),
                                                         '2015 and later': (0.8,
                                                                            0.8)},
                                   'system_control_range_res': {'B': {'f_ctrl_range': (0.57,
                                                                                       0.57)},
                                                                'C': {'f_ctrl_range': (0.85,
                                                                                       0.85)},
                                                                'D': {'f_ctrl_range': (1.0,
                                                                                       1.0)},
                                                                'A': {'f_ctrl_range': (1.0,
                                                                                       1.0)}},
                                   'system_control_range_nonres': {'D': {'f_ctrl_range': (0.8,
                                                                                          0.8)},
                                                                   'C': {'f_ctrl_range': (0.65,
                                                                                          0.65)},
                                                                   'B': {'f_ctrl_range': (0.85,
                                                                                          0.85)},
                                                                   'A': {'f_ctrl_range': (1.0,
                                                                                          1.0)}},
                                   'fan_pressure_range': {'res_mech': (50.0,
                                                                       50.0),
                                                          'nonres_intake': (100.0,
                                                                            100.0),
                                                          'nonres_exhaust': (150.0,
                                                                             150.0)},
                                   'hrv_sensible_eff_range': (0.75, 0.75),
                                   'system_type_map': {'residential': {'< 1945': {'Corner House': 'B',
                                                                                  'Apartment': 'C',
                                                                                  'Terrace or Semi-detached House': 'C',
                                                                                  'Detached House': 'D',
                                                                                  'Two-and-a-half-story House': 'A'},
                                                                       '1945 - 1964': {'Corner House': 'A',
                                                                                       'Apartment': 'C',
                                                                                       'Terrace or Semi-detached House': 'D',
                                                                                       'Detached House': 'D',
                                                                                       'Two-and-a-half-story House': 'C'},
                                                                       '1965 - 1974': {'Corner House': 'C',
                                                                                       'Apartment': 'B',
                                                                                       'Terrace or Semi-detached House': 'C',
                                                                                       'Detached House': 'D',
                                                                                       'Two-and-a-half-story House': 'A'},
                                                                       '1975 - 1991': {'Corner House': 'B',
                                                                                       'Apartment': 'C',
                                                                                       'Terrace or Semi-detached House': 'B',
                                                                                       'Detached House': 'C',
                                                                                       'Two-and-a-half-story House': 'A'},
                                                                       '1992 - 2005': {'Corner House': 'C',
                                                                                       'Apartment': 'A',
                                                                                       'Terrace or Semi-detached House': 'C',
                                                                                       'Detached House': 'D',
                                                                                       'Two-and-a-half-story House': 'D'},
                                                                       '2006 - 2014': {'Corner House': 'D',
                                                                                       'Apartment': 'D',
                                                                                       'Terrace or Semi-detached House': 'C',
                                                                                       'Detached House': 'C',
                                                                                       'Two-and-a-half-story House': 'A'},
                                                                       '2015 and later': {'Corner House': 'D',
                                                                                          'Apartment': 'C',
                                                                                          'Terrace or Semi-detached House': 'A',
                                                                                          'Detached House': 'B',
                                                                                          'Two-and-a-half-story House': 'D'}},
                                                       'non_residential': {'< 1945': {'Meeting Function': 'D',
                                                                                      'Healthcare Function': 'D',
                                                                                      'Sport Function': 'C',
                                                                                      'Cell Function': 'C',
                                                                                      'Retail Function': 'B',
                                                                                      'Industrial Function': 'B',
                                                                                      'Accommodation Function': 'A',
                                                                                      'Office Function': 'C',
                                                                                      'Education Function': 'A',
                                                                                      'Other Use Function': 'B'},
                                                                           '1945 - 1964': {'Meeting Function': 'C',
                                                                                           'Healthcare Function': 'D',
                                                                                           'Sport Function': 'B',
                                                                                           'Cell Function': 'C',
                                                                                           'Retail Function': 'B',
                                                                                           'Industrial Function': 'A',
                                                                                           'Accommodation Function': 'D',
                                                                                           'Office Function': 'D',
                                                                                           'Education Function': 'B',
                                                                                           'Other Use Function': 'A'},
                                                                           '1965 - 1974': {'Meeting Function': 'B',
                                                                                           'Healthcare Function': 'C',
                                                                                           'Sport Function': 'B',
                                                                                           'Cell Function': 'C',
                                                                                           'Retail Function': 'C',
                                                                                           'Industrial Function': 'C',
                                                                                           'Accommodation Function': 'B',
                                                                                           'Office Function': 'B',
                                                                                           'Education Function': 'D',
                                                                                           'Other Use Function': 'A'},
                                                                           '1975 - 1991': {'Meeting Function': 'C',
                                                                                           'Healthcare Function': 'D',
                                                                                           'Sport Function': 'B',
                                                                                           'Cell Function': 'C',
                                                                                           'Retail Function': 'B',
                                                                                           'Industrial Function': 'A',
                                                                                           'Accommodation Function': 'D',
                                                                                           'Office Function': 'D',
                                                                                           'Education Function': 'B',
                                                                                           'Other Use Function': 'A'},
                                                                           '1992 - 2005': {'Meeting Function': 'A',
                                                                                           'Healthcare Function': 'D',
                                                                                           'Sport Function': 'C',
                                                                                           'Cell Function': 'C',
                                                                                           'Retail Function': 'B',
                                                                                           'Industrial Function': 'B',
                                                                                           'Accommodation Function': 'A',
                                                                                           'Office Function': 'C',
                                                                                           'Education Function': 'A',
                                                                                           'Other Use Function': 'B'},
                                                                           '2006 - 2014': {'Meeting Function': 'C',
                                                                                           'Healthcare Function': 'D',
                                                                                           'Sport Function': 'B',
                                                                                           'Cell Function': 'C',
                                                                                           'Retail Function': 'B',
                                                                                           'Industrial Function': 'A',
                                                                                           'Accommodation Function': 'D',
                                                                                           'Office Function': 'D',
                                                                                           'Education Function': 'B',
                                                                                           'Other Use Function': 'A'},
                                                                           '2015 and later': {'Meeting Function': 'A',
                                                                                              'Healthcare Function': 'D',
                                                                                              'Sport Function': 'C',
                                                                                              'Cell Function': 'C',
                                                                                              'Retail Function': 'B',
                                                                                              'Industrial Function': 'B',
                                                                                              'Accommodation Function': 'A',
                                                                                              'Office Function': 'C',
                                                                                              'Education Function': 'A',
                                                                                              'Other Use Function': 'B'}}}}},
 'scenario2': {'post_calibration': {'residential_infiltration_range': {'Corner House': (1.3,
                                                                                        1.3),
                                                                       'Apartment': (0.9,
                                                                                     0.9),
                                                                       'Terrace or Semi-detached House': (1.1,
                                                                                                          1.1),
                                                                       'Detached House': (1.3,
                                                                                          1.3),
                                                                       'Two-and-a-half-story House': (1.2,
                                                                                                      1.2),
                                                                       'other_res': (1.1,
                                                                                     1.1)},
                                    'non_res_infiltration_range': {'Meeting Function': (0.6,
                                                                                        0.6),
                                                                   'Healthcare Function': (0.7,
                                                                                           0.7),
                                                                   'Sport Function': (0.5,
                                                                                      0.5),
                                                                   'Cell Function': (0.6,
                                                                                     0.6),
                                                                   'Retail Function': (0.7,
                                                                                       0.7),
                                                                   'Industrial Function': (0.7,
                                                                                           0.7),
                                                                   'Accommodation Function': (0.6,
                                                                                              0.6),
                                                                   'Office Function': (0.6,
                                                                                       0.6),
                                                                   'Education Function': (0.6,
                                                                                          0.6),
                                                                   'Other Use Function': (0.6,
                                                                                          0.6),
                                                                   'other_nonres': (0.6,
                                                                                    0.6)},
                                    'year_factor_range': {'< 1945': (2.2, 2.2),
                                                          '1945 - 1964': (1.9,
                                                                          1.9),
                                                          '1965 - 1974': (1.6,
                                                                          1.6),
                                                          '1975 - 1991': (1.4,
                                                                          1.4),
                                                          '1992 - 2005': (1.2,
                                                                          1.2),
                                                          '2006 - 2014': (1.0,
                                                                          1.0),
                                                          '2015 and later': (0.8,
                                                                             0.8)},
                                    'system_control_range_res': {'B': {'f_ctrl_range': (0.57,
                                                                                        0.57)},
                                                                 'C': {'f_ctrl_range': (0.85,
                                                                                        0.85)},
                                                                 'D': {'f_ctrl_range': (1.0,
                                                                                        1.0)},
                                                                 'A': {'f_ctrl_range': (1.0,
                                                                                        1.0)}},
                                    'system_control_range_nonres': {'D': {'f_ctrl_range': (0.8,
                                                                                           0.8)},
                                                                    'C': {'f_ctrl_range': (0.65,
                                                                                           0.65)},
                                                                    'B': {'f_ctrl_range': (0.85,
                                                                                           0.85)},
                                                                    'A': {'f_ctrl_range': (1.0,
                                                                                           1.0)}},
                                    'fan_pressure_range': {'res_mech': (50.0,
                                                                        50.0),
                                                           'nonres_intake': (100.0,
                                                                             100.0),
                                                           'nonres_exhaust': (150.0,
                                                                              150.0)},
                                    'hrv_sensible_eff_range': (0.75, 0.75),
                                    'system_type_map': {'residential': {'< 1945': {'Corner House': 'B',
                                                                                   'Apartment': 'C',
                                                                                   'Terrace or Semi-detached House': 'C',
                                                                                   'Detached House': 'D',
                                                                                   'Two-and-a-half-story House': 'A'},
                                                                        '1945 - 1964': {'Corner House': 'A',
                                                                                        'Apartment': 'C',
                                                                                        'Terrace or Semi-detached House': 'D',
                                                                                        'Detached House': 'D',
                                                                                        'Two-and-a-half-story House': 'C'},
                                                                        '1965 - 1974': {'Corner House': 'C',
                                                                                        'Apartment': 'B',
                                                                                        'Terrace or Semi-detached House': 'C',
                                                                                        'Detached House': 'D',
                                                                                        'Two-and-a-half-story House': 'A'},
                                                                        '1975 - 1991': {'Corner House': 'B',
                                                                                        'Apartment': 'C',
                                                                                        'Terrace or Semi-detached House': 'B',
                                                                                        'Detached House': 'C',
                                                                                        'Two-and-a-half-story House': 'A'},
                                                                        '1992 - 2005': {'Corner House': 'C',
                                                                                        'Apartment': 'A',
                                                                                        'Terrace or Semi-detached House': 'C',
                                                                                        'Detached House': 'D',
                                                                                        'Two-and-a-half-story House': 'D'},
                                                                        '2006 - 2014': {'Corner House': 'D',
                                                                                        'Apartment': 'D',
                                                                                        'Terrace or Semi-detached House': 'C',
                                                                                        'Detached House': 'C',
                                                                                        'Two-and-a-half-story House': 'A'},
                                                                        '2015 and later': {'Corner House': 'D',
                                                                                           'Apartment': 'C',
                                                                                           'Terrace or Semi-detached House': 'A',
                                                                                           'Detached House': 'B',
                                                                                           'Two-and-a-half-story House': 'D'}},
                                                        'non_residential': {'< 1945': {'Meeting Function': 'D',
                                                                                       'Healthcare Function': 'D',
                                                                                       'Sport Function': 'C',
                                                                                       'Cell Function': 'C',
                                                                                       'Retail Function': 'B',
                                                                                       'Industrial Function': 'B',
                                                                                       'Accommodation Function': 'A',
                                                                                       'Office Function': 'C',
                                                                                       'Education Function': 'A',
                                                                                       'Other Use Function': 'B'},
                                                                            '1945 - 1964': {'Meeting Function': 'C',
                                                                                            'Healthcare Function': 'D',
                                                                                            'Sport Function': 'B',
                                                                                            'Cell Function': 'C',
                                                                                            'Retail Function': 'B',
                                                                                            'Industrial Function': 'A',
                                                                                            'Accommodation Function': 'D',
                                                                                            'Office Function': 'D',
                                                                                            'Education Function': 'B',
                                                                                            'Other Use Function': 'A'},
                                                                            '1965 - 1974': {'Meeting Function': 'B',
                                                                                            'Healthcare Function': 'C',
                                                                                            'Sport Function': 'B',
                                                                                            'Cell Function': 'C',
                                                                                            'Retail Function': 'C',
                                                                                            'Industrial Function': 'C',
                                                                                            'Accommodation Function': 'B',
                                                                                            'Office Function': 'B',
                                                                                            'Education Function': 'D',
                                                                                            'Other Use Function': 'A'},
                                                                            '1975 - 1991': {'Meeting Function': 'C',
                                                                                            'Healthcare Function': 'D',
                                                                                            'Sport Function': 'B',
                                                                                            'Cell Function': 'C',
                                                                                            'Retail Function': 'B',
                                                                                            'Industrial Function': 'A',
                                                                                            'Accommodation Function': 'D',
                                                                                            'Office Function': 'D',
                                                                                            'Education Function': 'B',
                                                                                            'Other Use Function': 'A'},
                                                                            '1992 - 2005': {'Meeting Function': 'A',
                                                                                            'Healthcare Function': 'D',
                                                                                            'Sport Function': 'C',
                                                                                            'Cell Function': 'C',
                                                                                            'Retail Function': 'B',
                                                                                            'Industrial Function': 'B',
                                                                                            'Accommodation Function': 'A',
                                                                                            'Office Function': 'C',
                                                                                            'Education Function': 'A',
                                                                                            'Other Use Function': 'B'},
                                                                            '2006 - 2014': {'Meeting Function': 'C',
                                                                                            'Healthcare Function': 'D',
                                                                                            'Sport Function': 'B',
                                                                                            'Cell Function': 'C',
                                                                                            'Retail Function': 'B',
                                                                                            'Industrial Function': 'A',
                                                                                            'Accommodation Function': 'D',
                                                                                            'Office Function': 'D',
                                                                                            'Education Function': 'B',
                                                                                            'Other Use Function': 'A'},
                                                                            '2015 and later': {'Meeting Function': 'A',
                                                                                               'Healthcare Function': 'D',
                                                                                               'Sport Function': 'C',
                                                                                               'Cell Function': 'C',
                                                                                               'Retail Function': 'B',
                                                                                               'Industrial Function': 'B',
                                                                                               'Accommodation Function': 'A',
                                                                                               'Office Function': 'C',
                                                                                               'Education Function': 'A',
                                                                                               'Other Use Function': 'B'}}}},
               'pre_calibration': {'residential_infiltration_range': {'Corner House': (1.3,
                                                                                       1.3),
                                                                      'Apartment': (0.9,
                                                                                    0.9),
                                                                      'Terrace or Semi-detached House': (1.1,
                                                                                                         1.1),
                                                                      'Detached House': (1.3,
                                                                                         1.3),
                                                                      'Two-and-a-half-story House': (1.2,
                                                                                                     1.2),
                                                                      'other_res': (1.1,
                                                                                    1.1)},
                                   'non_res_infiltration_range': {'Meeting Function': (0.6,
                                                                                       0.6),
                                                                  'Healthcare Function': (0.7,
                                                                                          0.7),
                                                                  'Sport Function': (0.5,
                                                                                     0.5),
                                                                  'Cell Function': (0.6,
                                                                                    0.6),
                                                                  'Retail Function': (0.7,
                                                                                      0.7),
                                                                  'Industrial Function': (0.7,
                                                                                          0.7),
                                                                  'Accommodation Function': (0.6,
                                                                                             0.6),
                                                                  'Office Function': (0.6,
                                                                                      0.6),
                                                                  'Education Function': (0.6,
                                                                                         0.6),
                                                                  'Other Use Function': (0.6,
                                                                                         0.6),
                                                                  'other_nonres': (0.6,
                                                                                   0.6)},
                                   'year_factor_range': {'< 1945': (2.2, 2.2),
                                                         '1945 - 1964': (1.9,
                                                                         1.9),
                                                         '1965 - 1974': (1.6,
                                                                         1.6),
                                                         '1975 - 1991': (1.4,
                                                                         1.4),
                                                         '1992 - 2005': (1.2,
                                                                         1.2),
                                                         '2006 - 2014': (1.0,
                                                                         1.0),
                                                         '2015 and later': (0.8,
                                                                            0.8)},
                                   'system_control_range_res': {'B': {'f_ctrl_range': (0.57,
                                                                                       0.57)},
                                                                'C': {'f_ctrl_range': (0.85,
                                                                                       0.85)},
                                                                'D': {'f_ctrl_range': (1.0,
                                                                                       1.0)},
                                                                'A': {'f_ctrl_range': (1.0,
                                                                                       1.0)}},
                                   'system_control_range_nonres': {'D': {'f_ctrl_range': (0.8,
                                                                                          0.8)},
                                                                   'C': {'f_ctrl_range': (0.65,
                                                                                          0.65)},
                                                                   'B': {'f_ctrl_range': (0.85,
                                                                                          0.85)},
                                                                   'A': {'f_ctrl_range': (1.0,
                                                                                          1.0)}},
                                   'fan_pressure_range': {'res_mech': (50.0,
                                                                       50.0),
                                                          'nonres_intake': (100.0,
                                                                            100.0),
                                                          'nonres_exhaust': (150.0,
                                                                             150.0)},
                                   'hrv_sensible_eff_range': (0.75, 0.75),
                                   'system_type_map': {'residential': {'< 1945': {'Corner House': 'B',
                                                                                  'Apartment': 'C',
                                                                                  'Terrace or Semi-detached House': 'C',
                                                                                  'Detached House': 'D',
                                                                                  'Two-and-a-half-story House': 'A'},
                                                                       '1945 - 1964': {'Corner House': 'A',
                                                                                       'Apartment': 'C',
                                                                                       'Terrace or Semi-detached House': 'D',
                                                                                       'Detached House': 'D',
                                                                                       'Two-and-a-half-story House': 'C'},
                                                                       '1965 - 1974': {'Corner House': 'C',
                                                                                       'Apartment': 'B',
                                                                                       'Terrace or Semi-detached House': 'C',
                                                                                       'Detached House': 'D',
                                                                                       'Two-and-a-half-story House': 'A'},
                                                                       '1975 - 1991': {'Corner House': 'B',
                                                                                       'Apartment': 'C',
                                                                                       'Terrace or Semi-detached House': 'B',
                                                                                       'Detached House': 'C',
                                                                                       'Two-and-a-half-story House': 'A'},
                                                                       '1992 - 2005': {'Corner House': 'C',
                                                                                       'Apartment': 'A',
                                                                                       'Terrace or Semi-detached House': 'C',
                                                                                       'Detached House': 'D',
                                                                                       'Two-and-a-half-story House': 'D'},
                                                                       '2006 - 2014': {'Corner House': 'D',
                                                                                       'Apartment': 'D',
                                                                                       'Terrace or Semi-detached House': 'C',
                                                                                       'Detached House': 'C',
                                                                                       'Two-and-a-half-story House': 'A'},
                                                                       '2015 and later': {'Corner House': 'D',
                                                                                          'Apartment': 'C',
                                                                                          'Terrace or Semi-detached House': 'A',
                                                                                          'Detached House': 'B',
                                                                                          'Two-and-a-half-story House': 'D'}},
                                                       'non_residential': {'< 1945': {'Meeting Function': 'D',
                                                                                      'Healthcare Function': 'D',
                                                                                      'Sport Function': 'C',
                                                                                      'Cell Function': 'C',
                                                                                      'Retail Function': 'B',
                                                                                      'Industrial Function': 'B',
                                                                                      'Accommodation Function': 'A',
                                                                                      'Office Function': 'C',
                                                                                      'Education Function': 'A',
                                                                                      'Other Use Function': 'B'},
                                                                           '1945 - 1964': {'Meeting Function': 'C',
                                                                                           'Healthcare Function': 'D',
                                                                                           'Sport Function': 'B',
                                                                                           'Cell Function': 'C',
                                                                                           'Retail Function': 'B',
                                                                                           'Industrial Function': 'A',
                                                                                           'Accommodation Function': 'D',
                                                                                           'Office Function': 'D',
                                                                                           'Education Function': 'B',
                                                                                           'Other Use Function': 'A'},
                                                                           '1965 - 1974': {'Meeting Function': 'B',
                                                                                           'Healthcare Function': 'C',
                                                                                           'Sport Function': 'B',
                                                                                           'Cell Function': 'C',
                                                                                           'Retail Function': 'C',
                                                                                           'Industrial Function': 'C',
                                                                                           'Accommodation Function': 'B',
                                                                                           'Office Function': 'B',
                                                                                           'Education Function': 'D',
                                                                                           'Other Use Function': 'A'},
                                                                           '1975 - 1991': {'Meeting Function': 'C',
                                                                                           'Healthcare Function': 'D',
                                                                                           'Sport Function': 'B',
                                                                                           'Cell Function': 'C',
                                                                                           'Retail Function': 'B',
                                                                                           'Industrial Function': 'A',
                                                                                           'Accommodation Function': 'D',
                                                                                           'Office Function': 'D',
                                                                                           'Education Function': 'B',
                                                                                           'Other Use Function': 'A'},
                                                                           '1992 - 2005': {'Meeting Function': 'A',
                                                                                           'Healthcare Function': 'D',
                                                                                           'Sport Function': 'C',
                                                                                           'Cell Function': 'C',
                                                                                           'Retail Function': 'B',
                                                                                           'Industrial Function': 'B',
                                                                                           'Accommodation Function': 'A',
                                                                                           'Office Function': 'C',
                                                                                           'Education Function': 'A',
                                                                                           'Other Use Function': 'B'},
                                                                           '2006 - 2014': {'Meeting Function': 'C',
                                                                                           'Healthcare Function': 'D',
                                                                                           'Sport Function': 'B',
                                                                                           'Cell Function': 'C',
                                                                                           'Retail Function': 'B',
                                                                                           'Industrial Function': 'A',
                                                                                           'Accommodation Function': 'D',
                                                                                           'Office Function': 'D',
                                                                                           'Education Function': 'B',
                                                                                           'Other Use Function': 'A'},
                                                                           '2015 and later': {'Meeting Function': 'A',
                                                                                              'Healthcare Function': 'D',
                                                                                              'Sport Function': 'C',
                                                                                              'Cell Function': 'C',
                                                                                              'Retail Function': 'B',
                                                                                              'Industrial Function': 'B',
                                                                                              'Accommodation Function': 'A',
                                                                                              'Office Function': 'C',
                                                                                              'Education Function': 'A',
                                                                                              'Other Use Function': 'B'}}}}}}
