# Auto-generated from Excel

dhw_lookup = {'TABLE_13_1_KWH_PER_M2': {'Meeting Function': 2.8,
                           'Office Function': 1.4,
                           'Retail Function': 1.4,
                           'Healthcare Function': 15.3,
                           'Education Function': 1.4,
                           'Sport Function': 12.5,
                           'Cell Function': 4.2,
                           'Industrial Function': 1.2,
                           'Accommodation Function': 12.5,
                           'Other Use Function': 2.4},
 'pre_calibration': {'Corner House': {'occupant_density_m2_per_person_range': (None,
                                                                               None),
                                      'liters_per_person_per_day_range': (45,
                                                                          55),
                                      'default_tank_volume_liters_range': (180,
                                                                           220),
                                      'default_heater_capacity_w_range': (3500,
                                                                          4500),
                                      'setpoint_c_range': (58, 60),
                                      'usage_split_factor_range': (0.5, 0.7),
                                      'peak_hours_range': (1.5, 2.5),
                                      'sched_morning_range': (0.6, 0.8),
                                      'sched_peak_range': (0.9, 1.1),
                                      'sched_afternoon_range': (0.1, 0.3),
                                      'sched_evening_range': (0.5, 0.9)},
                     'Apartment': {'occupant_density_m2_per_person_range': (25.0,
                                                                            35.0),
                                   'liters_per_person_per_day_range': (45, 55),
                                   'default_tank_volume_liters_range': (900,
                                                                        1100),
                                   'default_heater_capacity_w_range': (18000,
                                                                       22000),
                                   'setpoint_c_range': (58, 60),
                                   'usage_split_factor_range': (0.5, 0.7),
                                   'peak_hours_range': (2.0, 3.0),
                                   'sched_morning_range': (0.5, 0.7),
                                   'sched_peak_range': (0.9, 1.1),
                                   'sched_afternoon_range': (0.2, 0.4),
                                   'sched_evening_range': (0.5, 0.8)},
                     'Terrace or Semi-detached House': {'occupant_density_m2_per_person_range': (None,
                                                                                                 None),
                                                        'liters_per_person_per_day_range': (45,
                                                                                            55),
                                                        'default_tank_volume_liters_range': (180,
                                                                                             250),
                                                        'default_heater_capacity_w_range': (3500,
                                                                                            5000),
                                                        'setpoint_c_range': (58,
                                                                             60),
                                                        'usage_split_factor_range': (0.5,
                                                                                     0.7),
                                                        'peak_hours_range': (2.0,
                                                                             3.0),
                                                        'sched_morning_range': (0.6,
                                                                                0.8),
                                                        'sched_peak_range': (0.9,
                                                                             1.1),
                                                        'sched_afternoon_range': (0.2,
                                                                                  0.4),
                                                        'sched_evening_range': (0.5,
                                                                                0.9)},
                     'Detached House': {'occupant_density_m2_per_person_range': (None,
                                                                                 None),
                                        'liters_per_person_per_day_range': (55,
                                                                            65),
                                        'default_tank_volume_liters_range': (250,
                                                                             350),
                                        'default_heater_capacity_w_range': (4000,
                                                                            5000),
                                        'setpoint_c_range': (58, 60),
                                        'usage_split_factor_range': (0.5, 0.7),
                                        'peak_hours_range': (2.0, 3.0),
                                        'sched_morning_range': (0.6, 0.8),
                                        'sched_peak_range': (0.9, 1.1),
                                        'sched_afternoon_range': (0.2, 0.3),
                                        'sched_evening_range': (0.6, 1.0)},
                     'Two-and-a-half-story House': {'occupant_density_m2_per_person_range': (None,
                                                                                             None),
                                                    'liters_per_person_per_day_range': (50,
                                                                                        60),
                                                    'default_tank_volume_liters_range': (220,
                                                                                         320),
                                                    'default_heater_capacity_w_range': (4000,
                                                                                        5000),
                                                    'setpoint_c_range': (58,
                                                                         60),
                                                    'usage_split_factor_range': (0.5,
                                                                                 0.7),
                                                    'peak_hours_range': (1.5,
                                                                         2.5),
                                                    'sched_morning_range': (0.6,
                                                                            0.8),
                                                    'sched_peak_range': (0.9,
                                                                         1.1),
                                                    'sched_afternoon_range': (0.2,
                                                                              0.4),
                                                    'sched_evening_range': (0.5,
                                                                            0.9)},
                     'Meeting Function': {'occupant_density_m2_per_person_range': (0.8,
                                                                                   1.2),
                                          'liters_per_person_per_day_range': (4,
                                                                              6),
                                          'default_tank_volume_liters_range': (400,
                                                                               600),
                                          'default_heater_capacity_w_range': (13000,
                                                                              17000),
                                          'setpoint_c_range': (58, 60),
                                          'usage_split_factor_range': (0.6,
                                                                       0.8),
                                          'peak_hours_range': (2.0, 3.0),
                                          'sched_morning_range': (0.1, 0.2),
                                          'sched_peak_range': (0.6, 0.8),
                                          'sched_afternoon_range': (0.1, 0.3),
                                          'sched_evening_range': (0.2, 0.5)},
                     'Healthcare Function': {'occupant_density_m2_per_person_range': (8.0,
                                                                                      30.0),
                                             'liters_per_person_per_day_range': (18,
                                                                                 70),
                                             'default_tank_volume_liters_range': (1000,
                                                                                  5000),
                                             'default_heater_capacity_w_range': (20000,
                                                                                 50000),
                                             'setpoint_c_range': (58, 65),
                                             'usage_split_factor_range': (0.6,
                                                                          0.8),
                                             'peak_hours_range': (2.0, 3.0),
                                             'sched_morning_range': (0.2, 0.4),
                                             'sched_peak_range': (0.6, 0.8),
                                             'sched_afternoon_range': (0.2,
                                                                       0.4),
                                             'sched_evening_range': (0.1, 0.3)},
                     'Sport Function': {'occupant_density_m2_per_person_range': (8.0,
                                                                                 12.0),
                                        'liters_per_person_per_day_range': (25,
                                                                            35),
                                        'default_tank_volume_liters_range': (2800,
                                                                             3200),
                                        'default_heater_capacity_w_range': (38000,
                                                                            42000),
                                        'setpoint_c_range': (58, 60),
                                        'usage_split_factor_range': (0.6, 0.8),
                                        'peak_hours_range': (2.0, 3.0),
                                        'sched_morning_range': (0.2, 0.4),
                                        'sched_peak_range': (0.6, 0.8),
                                        'sched_afternoon_range': (0.2, 0.4),
                                        'sched_evening_range': (0.3, 0.6)},
                     'Cell Function': {'occupant_density_m2_per_person_range': (10.0,
                                                                                20.0),
                                       'liters_per_person_per_day_range': (30,
                                                                           40),
                                       'default_tank_volume_liters_range': (1000,
                                                                            3000),
                                       'default_heater_capacity_w_range': (20000,
                                                                           40000),
                                       'setpoint_c_range': (58, 60),
                                       'usage_split_factor_range': (0.6, 0.8),
                                       'peak_hours_range': (2.0, 3.0),
                                       'sched_morning_range': (0.2, 0.4),
                                       'sched_peak_range': (0.7, 0.8),
                                       'sched_afternoon_range': (0.2, 0.4),
                                       'sched_evening_range': (0.4, 0.7)},
                     'Retail Function': {'occupant_density_m2_per_person_range': (4.0,
                                                                                  6.0),
                                         'liters_per_person_per_day_range': (4,
                                                                             6),
                                         'default_tank_volume_liters_range': (250,
                                                                              350),
                                         'default_heater_capacity_w_range': (9000,
                                                                             11000),
                                         'setpoint_c_range': (58, 60),
                                         'usage_split_factor_range': (0.6, 0.8),
                                         'peak_hours_range': (2.0, 3.0),
                                         'sched_morning_range': (0.1, 0.3),
                                         'sched_peak_range': (0.5, 0.7),
                                         'sched_afternoon_range': (0.2, 0.4),
                                         'sched_evening_range': (0.1, 0.2)},
                     'Industrial Function': {'occupant_density_m2_per_person_range': (12.0,
                                                                                      30.0),
                                             'liters_per_person_per_day_range': (10,
                                                                                 20),
                                             'default_tank_volume_liters_range': (500,
                                                                                  2000),
                                             'default_heater_capacity_w_range': (10000,
                                                                                 30000),
                                             'setpoint_c_range': (58, 60),
                                             'usage_split_factor_range': (0.6,
                                                                          0.8),
                                             'peak_hours_range': (2.0, 3.0),
                                             'sched_morning_range': (0.2, 0.3),
                                             'sched_peak_range': (0.6, 0.7),
                                             'sched_afternoon_range': (0.2,
                                                                       0.4),
                                             'sched_evening_range': (0.2, 0.3)},
                     'Accommodation Function': {'occupant_density_m2_per_person_range': (15.0,
                                                                                         25.0),
                                                'liters_per_person_per_day_range': (50,
                                                                                    70),
                                                'default_tank_volume_liters_range': (1800,
                                                                                     2200),
                                                'default_heater_capacity_w_range': (28000,
                                                                                    32000),
                                                'setpoint_c_range': (58, 60),
                                                'usage_split_factor_range': (0.6,
                                                                             0.8),
                                                'peak_hours_range': (2.0, 3.0),
                                                'sched_morning_range': (0.2,
                                                                        0.4),
                                                'sched_peak_range': (0.8, 1.0),
                                                'sched_afternoon_range': (0.2,
                                                                          0.4),
                                                'sched_evening_range': (0.4,
                                                                        0.7)},
                     'Office Function': {'occupant_density_m2_per_person_range': (12.0,
                                                                                  18.0),
                                         'liters_per_person_per_day_range': (8,
                                                                             12),
                                         'default_tank_volume_liters_range': (250,
                                                                              350),
                                         'default_heater_capacity_w_range': (7000,
                                                                             9000),
                                         'setpoint_c_range': (58, 62),
                                         'usage_split_factor_range': (0.6, 0.8),
                                         'peak_hours_range': (2.0, 3.0),
                                         'sched_morning_range': (0.1, 0.2),
                                         'sched_peak_range': (0.5, 0.7),
                                         'sched_afternoon_range': (0.2, 0.4),
                                         'sched_evening_range': (0.05, 0.2)},
                     'Education Function': {'occupant_density_m2_per_person_range': (6.0,
                                                                                     10.0),
                                            'liters_per_person_per_day_range': (8,
                                                                                12),
                                            'default_tank_volume_liters_range': (400,
                                                                                 600),
                                            'default_heater_capacity_w_range': (9000,
                                                                                11000),
                                            'setpoint_c_range': (58, 60),
                                            'usage_split_factor_range': (0.6,
                                                                         0.8),
                                            'peak_hours_range': (2.0, 3.0),
                                            'sched_morning_range': (0.1, 0.3),
                                            'sched_peak_range': (0.5, 0.7),
                                            'sched_afternoon_range': (0.2, 0.4),
                                            'sched_evening_range': (0.1, 0.2)},
                     'Other Use Function': {'occupant_density_m2_per_person_range': (5.0,
                                                                                     15.0),
                                            'liters_per_person_per_day_range': (5,
                                                                                15),
                                            'default_tank_volume_liters_range': (300,
                                                                                 600),
                                            'default_heater_capacity_w_range': (9000,
                                                                                15000),
                                            'setpoint_c_range': (58, 60),
                                            'usage_split_factor_range': (0.5,
                                                                         0.7),
                                            'peak_hours_range': (2.0, 2.5),
                                            'sched_morning_range': (0.1, 0.2),
                                            'sched_peak_range': (0.5, 0.7),
                                            'sched_afternoon_range': (0.2, 0.4),
                                            'sched_evening_range': (0.2, 0.3)}},
 'post_calibration': {'Corner House': {'occupant_density_m2_per_person_range': (None,
                                                                                None),
                                       'liters_per_person_per_day_range': (50,
                                                                           50),
                                       'default_tank_volume_liters_range': (200,
                                                                            200),
                                       'default_heater_capacity_w_range': (4000,
                                                                           4000),
                                       'setpoint_c_range': (60, 60),
                                       'usage_split_factor_range': (0.6, 0.6),
                                       'peak_hours_range': (2.0, 2.0),
                                       'sched_morning_range': (0.7, 0.7),
                                       'sched_peak_range': (1.0, 1.0),
                                       'sched_afternoon_range': (0.2, 0.2),
                                       'sched_evening_range': (0.8, 0.8)},
                      'Apartment': {'occupant_density_m2_per_person_range': (30.0,
                                                                             30.0),
                                    'liters_per_person_per_day_range': (50, 50),
                                    'default_tank_volume_liters_range': (1000,
                                                                         1000),
                                    'default_heater_capacity_w_range': (20000,
                                                                        20000),
                                    'setpoint_c_range': (60, 60),
                                    'usage_split_factor_range': (0.6, 0.6),
                                    'peak_hours_range': (2.0, 2.0),
                                    'sched_morning_range': (0.7, 0.7),
                                    'sched_peak_range': (1.0, 1.0),
                                    'sched_afternoon_range': (0.2, 0.2),
                                    'sched_evening_range': (0.8, 0.8)},
                      'Terrace or Semi-detached House': {'occupant_density_m2_per_person_range': (None,
                                                                                                  None),
                                                         'liters_per_person_per_day_range': (50,
                                                                                             50),
                                                         'default_tank_volume_liters_range': (200,
                                                                                              200),
                                                         'default_heater_capacity_w_range': (4000,
                                                                                             4000),
                                                         'setpoint_c_range': (60,
                                                                              60),
                                                         'usage_split_factor_range': (0.6,
                                                                                      0.6),
                                                         'peak_hours_range': (2.0,
                                                                              2.0),
                                                         'sched_morning_range': (0.7,
                                                                                 0.7),
                                                         'sched_peak_range': (1.0,
                                                                              1.0),
                                                         'sched_afternoon_range': (0.2,
                                                                                   0.2),
                                                         'sched_evening_range': (0.8,
                                                                                 0.8)},
                      'Detached House': {'occupant_density_m2_per_person_range': (None,
                                                                                  None),
                                         'liters_per_person_per_day_range': (60,
                                                                             60),
                                         'default_tank_volume_liters_range': (300,
                                                                              300),
                                         'default_heater_capacity_w_range': (5000,
                                                                             5000),
                                         'setpoint_c_range': (60, 60),
                                         'usage_split_factor_range': (0.6, 0.6),
                                         'peak_hours_range': (2.5, 2.5),
                                         'sched_morning_range': (0.7, 0.7),
                                         'sched_peak_range': (1.0, 1.0),
                                         'sched_afternoon_range': (0.2, 0.2),
                                         'sched_evening_range': (0.8, 0.8)},
                      'Two-and-a-half-story House': {'occupant_density_m2_per_person_range': (None,
                                                                                              None),
                                                     'liters_per_person_per_day_range': (55,
                                                                                         55),
                                                     'default_tank_volume_liters_range': (250,
                                                                                          250),
                                                     'default_heater_capacity_w_range': (4500,
                                                                                         4500),
                                                     'setpoint_c_range': (60,
                                                                          60),
                                                     'usage_split_factor_range': (0.6,
                                                                                  0.6),
                                                     'peak_hours_range': (2.0,
                                                                          2.0),
                                                     'sched_morning_range': (0.7,
                                                                             0.7),
                                                     'sched_peak_range': (1.0,
                                                                          1.0),
                                                     'sched_afternoon_range': (0.2,
                                                                               0.2),
                                                     'sched_evening_range': (0.8,
                                                                             0.8)},
                      'Meeting Function': {'occupant_density_m2_per_person_range': (1.0,
                                                                                    1.0),
                                           'liters_per_person_per_day_range': (5,
                                                                               5),
                                           'default_tank_volume_liters_range': (500,
                                                                                500),
                                           'default_heater_capacity_w_range': (15000,
                                                                               15000),
                                           'setpoint_c_range': (60, 60),
                                           'usage_split_factor_range': (0.6,
                                                                        0.6),
                                           'peak_hours_range': (2.0, 2.0),
                                           'sched_morning_range': (0.2, 0.2),
                                           'sched_peak_range': (0.6, 0.6),
                                           'sched_afternoon_range': (0.2, 0.2),
                                           'sched_evening_range': (0.5, 0.5)},
                      'Healthcare Function': {'occupant_density_m2_per_person_range': (20.0,
                                                                                       20.0),
                                              'liters_per_person_per_day_range': (60,
                                                                                  60),
                                              'default_tank_volume_liters_range': (3000,
                                                                                   3000),
                                              'default_heater_capacity_w_range': (40000,
                                                                                  40000),
                                              'setpoint_c_range': (65, 65),
                                              'usage_split_factor_range': (0.7,
                                                                           0.7),
                                              'peak_hours_range': (3.0, 3.0),
                                              'sched_morning_range': (0.3, 0.3),
                                              'sched_peak_range': (0.7, 0.7),
                                              'sched_afternoon_range': (0.3,
                                                                        0.3),
                                              'sched_evening_range': (0.5,
                                                                      0.5)},
                      'Sport Function': {'occupant_density_m2_per_person_range': (10.0,
                                                                                  10.0),
                                         'liters_per_person_per_day_range': (30,
                                                                             30),
                                         'default_tank_volume_liters_range': (3000,
                                                                              3000),
                                         'default_heater_capacity_w_range': (40000,
                                                                             40000),
                                         'setpoint_c_range': (60, 60),
                                         'usage_split_factor_range': (0.6, 0.6),
                                         'peak_hours_range': (2.0, 2.0),
                                         'sched_morning_range': (0.3, 0.3),
                                         'sched_peak_range': (0.7, 0.7),
                                         'sched_afternoon_range': (0.3, 0.3),
                                         'sched_evening_range': (0.6, 0.6)},
                      'Cell Function': {'occupant_density_m2_per_person_range': (15.0,
                                                                                 15.0),
                                        'liters_per_person_per_day_range': (35,
                                                                            35),
                                        'default_tank_volume_liters_range': (2000,
                                                                             2000),
                                        'default_heater_capacity_w_range': (30000,
                                                                            30000),
                                        'setpoint_c_range': (60, 60),
                                        'usage_split_factor_range': (0.6, 0.6),
                                        'peak_hours_range': (2.5, 2.5),
                                        'sched_morning_range': (0.3, 0.3),
                                        'sched_peak_range': (0.7, 0.7),
                                        'sched_afternoon_range': (0.3, 0.3),
                                        'sched_evening_range': (0.5, 0.5)},
                      'Retail Function': {'occupant_density_m2_per_person_range': (5.0,
                                                                                   5.0),
                                          'liters_per_person_per_day_range': (5,
                                                                              5),
                                          'default_tank_volume_liters_range': (300,
                                                                               300),
                                          'default_heater_capacity_w_range': (10000,
                                                                              10000),
                                          'setpoint_c_range': (60, 60),
                                          'usage_split_factor_range': (0.6,
                                                                       0.6),
                                          'peak_hours_range': (2.0, 2.0),
                                          'sched_morning_range': (0.1, 0.1),
                                          'sched_peak_range': (0.7, 0.7),
                                          'sched_afternoon_range': (0.2, 0.2),
                                          'sched_evening_range': (0.1, 0.1)},
                      'Industrial Function': {'occupant_density_m2_per_person_range': (20.0,
                                                                                       20.0),
                                              'liters_per_person_per_day_range': (15,
                                                                                  15),
                                              'default_tank_volume_liters_range': (1000,
                                                                                   1000),
                                              'default_heater_capacity_w_range': (20000,
                                                                                  20000),
                                              'setpoint_c_range': (60, 60),
                                              'usage_split_factor_range': (0.6,
                                                                           0.6),
                                              'peak_hours_range': (2.0, 2.0),
                                              'sched_morning_range': (0.2, 0.2),
                                              'sched_peak_range': (0.6, 0.6),
                                              'sched_afternoon_range': (0.2,
                                                                        0.2),
                                              'sched_evening_range': (0.3,
                                                                      0.3)},
                      'Accommodation Function': {'occupant_density_m2_per_person_range': (20.0,
                                                                                          20.0),
                                                 'liters_per_person_per_day_range': (60,
                                                                                     60),
                                                 'default_tank_volume_liters_range': (2000,
                                                                                      2000),
                                                 'default_heater_capacity_w_range': (30000,
                                                                                     30000),
                                                 'setpoint_c_range': (60, 60),
                                                 'usage_split_factor_range': (0.6,
                                                                              0.6),
                                                 'peak_hours_range': (2.0, 2.0),
                                                 'sched_morning_range': (0.3,
                                                                         0.3),
                                                 'sched_peak_range': (0.8, 0.8),
                                                 'sched_afternoon_range': (0.3,
                                                                           0.3),
                                                 'sched_evening_range': (0.6,
                                                                         0.6)},
                      'Office Function': {'occupant_density_m2_per_person_range': (15.0,
                                                                                   15.0),
                                          'liters_per_person_per_day_range': (10,
                                                                              10),
                                          'default_tank_volume_liters_range': (300,
                                                                               300),
                                          'default_heater_capacity_w_range': (8000,
                                                                              8000),
                                          'setpoint_c_range': (60, 60),
                                          'usage_split_factor_range': (0.7,
                                                                       0.7),
                                          'peak_hours_range': (2.5, 2.5),
                                          'sched_morning_range': (0.15, 0.15),
                                          'sched_peak_range': (0.6, 0.6),
                                          'sched_afternoon_range': (0.3, 0.3),
                                          'sched_evening_range': (0.1, 0.1)},
                      'Education Function': {'occupant_density_m2_per_person_range': (8.0,
                                                                                      8.0),
                                             'liters_per_person_per_day_range': (10,
                                                                                 10),
                                             'default_tank_volume_liters_range': (500,
                                                                                  500),
                                             'default_heater_capacity_w_range': (10000,
                                                                                 10000),
                                             'setpoint_c_range': (60, 60),
                                             'usage_split_factor_range': (0.6,
                                                                          0.6),
                                             'peak_hours_range': (2.0, 2.0),
                                             'sched_morning_range': (0.2, 0.2),
                                             'sched_peak_range': (0.6, 0.6),
                                             'sched_afternoon_range': (0.2,
                                                                       0.2),
                                             'sched_evening_range': (0.1, 0.1)},
                      'Other Use Function': {'occupant_density_m2_per_person_range': (10.0,
                                                                                      10.0),
                                             'liters_per_person_per_day_range': (10,
                                                                                 10),
                                             'default_tank_volume_liters_range': (400,
                                                                                  400),
                                             'default_heater_capacity_w_range': (10000,
                                                                                 10000),
                                             'setpoint_c_range': (60, 60),
                                             'usage_split_factor_range': (0.6,
                                                                          0.6),
                                             'peak_hours_range': (2.0, 2.0),
                                             'sched_morning_range': (0.2, 0.2),
                                             'sched_peak_range': (0.6, 0.6),
                                             'sched_afternoon_range': (0.2,
                                                                       0.2),
                                             'sched_evening_range': (0.3,
                                                                     0.3)}}}
